M48
; DRILL file KiCad 10.0.1 date 2026-05-22T20:49:39
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-05-22T20:49:39+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0295
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0630
%
G90
G05
T1
X2.5692Y-5.3258
X2.5692Y-5.5541
X5.1713Y-3.8209
X5.1713Y-4.0492
T2
X5.1839Y-3.6713
T3
X5.1839Y-2.8839
M30
